### ISSUE TITLE
Line 61 of`start_spark_cluster.sh` will fail if the host machine has set `http_proxy` environment variable

### ISSUE THREAD

**Issue by soulmachine** [amplab/docker-scripts#12]
Line 61 of  `start_spark_cluster.sh` will fail if the host machine has set `http_proxy` environment variable, because the proxy server could not connect to `MASTER_IP`, which is a private IP

**Comment by AndreSchumacher** [comment]
Thanks, I'll add the "--no-proxy" argument to the wget statement. Did you find any other spots that have the same problem?

**Comment by AndreSchumacher** [comment]
I'm closing this now since I believe the only two HTTP traffic related places were now fixed.
