### ISSUE TITLE
Not able to pull shark 0.8.0 image

### ISSUE THREAD

**Issue by bzz** [amplab/docker-scripts#18]
```
$ docker -v
Docker version 0.7.0, build 0d078b6

$ sudo docker pull -t="0.8.0" amplab/shark-master
Pulling repository amplab/shark-master
2013/12/03 10:58:32 Server error: 404 trying to fetch remote history for amplab/shark-master
```

same command works well for amplab/spark-master image

**Comment by AndreSchumacher** [comment]
@alexander-bzz Can you try again? I just re-pushed the Shark images. I'm not quite sure what happened but maybe these got accidentally deleted during the last time I updated them.

Note that there is still the issue with the newer Docker versions and the name resolution of the driver/shell. As a temporary workaround ssh into the master and start the shell there (see below). This should be fixed soon.

```
ssh -i $HOME/docker-scripts/deploy/../apache-hadoop-hdfs-precise/files/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@172.17.0.18

cd /opt/metastore && sudo -u hdfs /opt/shark-0.8.0/bin/shark
```

(if ssh doesn't work make sure the file permission of id_rsa are set to 0700)

**Comment by bzz** [comment]
Ok, thank for quick response @AndreSchumacher !
can successfully pull sark 0.8.0 now (server, worker and shell).

And you are right, from shark-shell image it is not possible to run any queries at list with Docker 0.7 but the workaround as ssh to master and start shell there works.

So should we close this issue now and open another on new docker version and the name resolution for the driver/shell?

**Comment by AndreSchumacher** [comment]
Great to hear it worked. About the other issue: I plan to push some changes later today that should resolve the name resolution issue. It seems that the driver/shell needs to be able to be resolved via the nameserver as well so I had to do some changes to the way the shell is started. So maybe no need to post a new issue, I will raise this point in the docs. Also the blog post should be changed.
