### ISSUE TITLE
really simple doc issue

### ISSUE THREAD

**Issue by rseymour** [amplab/docker-scripts#37]
The 1.0.0 boot2docker vm doesn't have bash installed!  So one must use tcb-ab to install bash.

**Comment by AndreSchumacher** [comment]
Yeah, noticed the same today. I wonder why they use this kind of basic imagine. Also the memory should be increased to at least 2GB. I will update the docs together with the images hopefully tomorrow.

**Comment by AndreSchumacher** [comment]
I updating the README and therefore close this now.
